name: Build Electron

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Config git
        run: git config --global core.autocrlf false
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup yarn
        run: npm i -g yarn
      - name: Cache NPM dependencies
        uses: actions/cache@v3.2.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip green
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: d://green_${{ env.GITHUB_SHA }}.zip
          directory: 'dist_electron/win-unpacked'
      - name: Upload green
        uses: actions/upload-artifact@v3
        with:
          name: windows-green-${{ env.GITHUB_SHA }}
          path: |
            d://green_${{ env.GITHUB_SHA }}.zip
